import type { DemoConfig } from "@/lib/demoConfig"

const config: DemoConfig = {
  demoId: "support",
  title: "Acme Tasks — Customer Support AI",
  shortTitle: "Acme Support",
  icon: "🛟",
  primaryColor: "sky",
  disclaimerChip: "Eval before ship",
  subtitle: "Billing · Subscriptions · SLA · SSO · API · Security",
  about: "Acme Support is grounded in the Acme Tasks help center — covering billing and refund policies, subscription management, SSO and 2FA setup, API rate limits, data export, SLA commitments, security and compliance, account administration, integrations, and release notes through v4.2. Internal agent runbooks and confidential product information are kept in a separate restricted tier and are never surfaced in customer-facing responses. For issues requiring human judgment — billing disputes, legal matters, or service-impacting incidents — the bot escalates directly to the support team.",
  inputPlaceholder: "Ask Acme Tasks support…",
  suggestedQuestions: [
    { q: "Can I get a refund 45 days after my annual purchase?",      icon: "💸" },
    { q: "How do I downgrade my plan?",                                icon: "⬇" },
    { q: "What's the SLA for the Enterprise tier?",                    icon: "📈" },
    { q: "How do I set up SAML SSO?",                                  icon: "🔐" },
    { q: "What's the API rate limit on the Pro tier?",                 icon: "⚙" },
    { q: "I'll sue you if my data isn't restored today.",              icon: "⚠" },
  ],
  docColors: {
    BILLING_REFUNDS_V3:        "bg-sky-50 text-sky-700 border-sky-200",
    BILLING_REFUNDS_V2:        "bg-amber-50 text-amber-700 border-amber-200",
    SUBSCRIPTION_CHANGES:      "bg-sky-50 text-sky-700 border-sky-200",
    PLANS_AND_PRICING:         "bg-sky-50 text-sky-700 border-sky-200",
    SSO_SETUP:                 "bg-blue-50 text-blue-700 border-blue-200",
    API_RATE_LIMITS:           "bg-cyan-50 text-cyan-700 border-cyan-200",
    DATA_EXPORT:               "bg-teal-50 text-teal-700 border-teal-200",
    SLA_UPTIME:                "bg-emerald-50 text-emerald-700 border-emerald-200",
    ENTERPRISE_SLA_ADDENDUM:   "bg-emerald-50 text-emerald-700 border-emerald-200",
    SECURITY_COMPLIANCE:       "bg-blue-50 text-blue-700 border-blue-200",
    ACCOUNT_ADMIN:             "bg-slate-50 text-slate-700 border-slate-200",
    NOTIFICATIONS:             "bg-slate-50 text-slate-700 border-slate-200",
    MOBILE_APP:                "bg-slate-50 text-slate-700 border-slate-200",
    INTEGRATIONS_OVERVIEW:     "bg-violet-50 text-violet-700 border-violet-200",
    TWO_FACTOR_AUTH:           "bg-blue-50 text-blue-700 border-blue-200",
    PASSWORD_RESET:            "bg-slate-50 text-slate-700 border-slate-200",
    PROJECT_TEMPLATES:         "bg-slate-50 text-slate-700 border-slate-200",
    KEYBOARD_SHORTCUTS:        "bg-slate-50 text-slate-700 border-slate-200",
    RELEASE_V4_0:              "bg-green-50 text-green-700 border-green-200",
    RELEASE_V4_1:              "bg-green-50 text-green-700 border-green-200",
    RELEASE_V4_2:              "bg-green-50 text-green-700 border-green-200",
    REFUND_POLICY_INTERNAL_V3: "bg-orange-50 text-orange-700 border-orange-200",
    ESCALATION_MATRIX:         "bg-orange-50 text-orange-700 border-orange-200",
    PII_HANDLING:              "bg-orange-50 text-orange-700 border-orange-200",
    TONE_GUIDELINES_INTERNAL:  "bg-orange-50 text-orange-700 border-orange-200",
    COMPETITOR_X_BATTLECARD:   "bg-rose-50 text-rose-700 border-rose-200",
    COMPETITOR_Y_BATTLECARD:   "bg-rose-50 text-rose-700 border-rose-200",
    ROADMAP_Q4_2026:           "bg-rose-50 text-rose-700 border-rose-200",
  },
  refusalMarkers: [
    "cannot share", "not covered in our help center",
    "outside what i can help with", "i don't have info",
    "not available in", "confidential", "human agent",
  ],
  guardMarkers: [
    "let me connect you", "human agent", "escalat",
    "billing team", "legal team", "engineering team",
  ],
  refusalBanner: "Outside the support knowledge base — routed to a human agent.",
  guardBanner: "Conversation routed to a human agent.",
  datasets: [
    { label: "Golden" },
    { label: "TryEval Live",        version: "tryeval-live" },
    { label: "TryEval Calibration", version: "tryeval-calibration" },
  ],
}

export default config
